#!/usr/bin/python
# -*- coding: utf-8 -*-
# vim: ts=4 
###
#
# Copyright (c) 2010 J. Félix Ontañón
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors : J. Félix Ontañón <fontanon@emergya.es>
# 
###

import sys
import gtk
import gobject
import logging

from udevdiscover import DeviceFinder
from udevdiscover.utils import GConfStore, TextBufferHandler

# FIXME: This path needs to be assigned at installing time
UDEVMAN_UI = 'udev-discover.ui'
GCONF_KEY = '/apps/udevdiscover'

DEFAULT_SUBSYSTEMS = ['usb', 'pci', 'net', 'power_supply', 'block', 'sound', 
    'input', 'serio', 'platform', 'tty', 'pnp', 'drm', 'video4linux', 'rfkill',
    'bluetooth', 'leds', 'dvb', 'acpi']

TEXTBUFFER_LOGGER = 'udevdiscover'
LOG_LEVEL = logging.DEBUG
LOG_FORMAT = '%(asctime)s %(levelname)s - %(message)s'
LOG_DATE_FORMAT = '%H:%M:%S'

PATH_COL, ICON_COL, NAME_COL, SUBSYSTEM_COL, VISIBLE_COL = range(5)

# Load icons
theme = gtk.icon_theme_get_default()
device_icon = theme.load_icon('gtk-dialog-question', 24, 0)

class UDevDiscoverGUI(GConfStore):

    defaults = {
            'window_width': 600,
            'window_height': 400,
            'devices_hpaned': 150,
            'parent_tree': True,
            'expanded': True,
            'eventslog_vpaned': 350,
            'eventslog_expanded': True,
            'follownew': True,
            'followchanged': True,
    }

    def __init__(self):
        GConfStore.__init__(self, GCONF_KEY)
        self.rows = {}

        self.builder = gtk.Builder()
        if not self.builder.add_from_file(UDEVMAN_UI):
            raise 'Cant load %s' % UDEVMAN_UI
        self.builder.connect_signals(self)

        self.main_window = self.builder.get_object('main_window')
        self.devices_hpaned = self.builder.get_object('devices_hpaned')
        self.eventslog_vpaned = self.builder.get_object('eventslog_vpaned')
        self.devices_tv = self.builder.get_object('devices_tv')
        self.devices_treestore = self.builder.get_object('devices_treestore')
        self.deviceprop_tv = self.builder.get_object('deviceprop_tv')
        self.deviceprop_store = self.builder.get_object('deviceprop_store')
        self.devicename_label = self.builder.get_object('devicename_label')
        self.devicedesc_label = self.builder.get_object('devicedesc_label')
        self.device_image = self.builder.get_object('device_image')
        self.parents_toolbtn = self.builder.get_object('parents_toolbtn')
        self.expand_toggleaction = self.builder.get_object('expand_toggleaction')
        self.showparents_toggleaction = self.builder.get_object('showparents_toggleaction')
        self.eventslog_expander = self.builder.get_object('eventslog_expander')
        self.eventslog_textbuffer = self.builder.get_object('eventslog_textbuffer')
        self.follownew_toggleaction = self.builder.get_object('follownew_toggleaction')
        self.followchanged_toggleaction = \
            self.builder.get_object('followchanged_toggleaction')
        self.summary_scrollwindow = self.builder.get_object('summary_scrollwindow')
        self.devicepropsum_label = self.builder.get_object('devicepropsum_label')
        self.search_entry = self.builder.get_object('search_entry')

        # About dialog
        self.about_dialog = self.builder.get_object('about_dialog')
        self.about_dialog.connect('response', lambda d, r: d.hide())

        # Store main window width/height
        def catch_window_size(widget, allocate, options):
            options['window_width'] = allocate.width
            options['window_height'] = allocate.height

        self.main_window.connect('size_allocate', catch_window_size, 
                self.options)

        self.loadconf()
        self.main_window.resize(self.options['window_width'], 
            self.options['window_height'])
        self.devices_hpaned.set_position(self.options['devices_hpaned'])
        self.eventslog_vpaned.set_position(self.options['eventslog_vpaned'])
        self.eventslog_expander.set_expanded(self.options['eventslog_expanded'])

        # Sets up the logger
        self.logger = logging.getLogger(TEXTBUFFER_LOGGER)
        self.logger.setLevel(LOG_LEVEL)
        handler = TextBufferHandler(self.eventslog_textbuffer)
        handler.setFormatter(logging.Formatter(LOG_FORMAT,
            datefmt=LOG_DATE_FORMAT))
        self.logger.addHandler(handler)

        # Populate treeview
        self.device_finder = DeviceFinder()
        self.device_finder.scan_subsystems(DEFAULT_SUBSYSTEMS, 
            self.options['parent_tree'])
        self.device_finder.connect('added', self.new_device)
        self.device_finder.connect('removed', self.removed_device)
        self.device_finder.connect('changed', self.changed_device)
        self.populate(self.device_finder.get_devices())

        self.parents_toolbtn.set_active(self.options['parent_tree'])
        self.expand_toggleaction.set_active(self.options['expanded'])
        self.expand_toggleaction_toggled_cb(self.expand_toggleaction)
        self.follownew_toggleaction.set_active(self.options['follownew'])
        self.followchanged_toggleaction.set_active(self.options['followchanged'])

        self.search_entry.set_property('primary-icon-sensitive',False)
        self.search_entry.set_property('secondary-icon-sensitive',False)

    def new_device(self, device_finder, device):
        row_ref = self.add_new_device(device)

        if self.options['expanded']:
            self.devices_tv.expand_to_path(row_ref.get_path())

        if self.options['follownew']:
            self.devices_tv.set_cursor(row_ref.get_path())

        self.logger.info('Device added: %s' % device.nice_label)

    def removed_device(self, device_finder, device):
        if self.rows.has_key(device.path):
            ref_row = self.rows[device.path]
            treeiter = self.devices_treestore.get_iter(ref_row.get_path())
            self.devices_treestore.remove(treeiter)
            del(self.rows[device.path])

        self.logger.info('Device removed: %s' % device.nice_label)

    def changed_device(self, device_finder, device):
        if self.rows.has_key(device.path):
            # Remove from tree first
            ref_row = self.rows[device.path]
            treeiter = self.devices_treestore.get_iter(ref_row.get_path())
            self.devices_treestore.remove(treeiter)
            del(self.rows[device.path])
            # Add again
            row_ref = self.add_new_device(device)

            if self.options['expanded']:
                self.devices_tv.expand_to_path(row_ref.get_path())

            if self.options['followchanged']:
                self.devices_tv.set_cursor(row_ref.get_path())

        self.logger.info('Device changed: %s' % device.nice_label)

    def populate(self, devices):
        self.devices_treestore.clear()
        self.rows = {}

        for device in devices:
            self.add_new_device(device)

    def add_new_device(self, device):
        device_icon = theme.load_icon(device.icon, 24, 0)
        if device.parent == None:
            treeiter = self.devices_treestore.append(None, [device.path, 
                device_icon, device.nice_label, device.subsystem, False])
        else:
            if self.rows.has_key(device.parent.path):
                parent_treeiter = self.devices_treestore.get_iter(
                    self.rows[device.parent.path].get_path())
                treeiter = self.devices_treestore.append(parent_treeiter, 
                    [device.path, device_icon, device.nice_label, 
                    device.subsystem, False])
            else:
                treeiter = self.devices_treestore.append(None, [device.path, 
                    device_icon, device.nice_label, device.subsystem, False])
        
        self.rows[device.path] = gtk.TreeRowReference(self.devices_treestore,
            self.devices_treestore.get_path(treeiter))

        return self.rows[device.path]

    def showparents_toggleaction_toggled_cb(self, action):
        self.options['parent_tree'] = action.get_active()
        self.device_finder.scan_subsystems(DEFAULT_SUBSYSTEMS, 
            self.options['parent_tree'])

        self.populate(self.device_finder.get_devices())
        self.expand_toggleaction_toggled_cb(self.expand_toggleaction)

    def expand_toggleaction_toggled_cb(self, action):
        if action.get_active():
            self.devices_tv.expand_all()
        else:
            self.devices_tv.collapse_all()

        self.options['expanded'] = self.expand_toggleaction.get_active()

    def follownew_toggleaction_toggled_cb(self, action):
        self.options['follownew'] = self.follownew_toggleaction.get_active()

    def followchanged_toggleaction_toggled_cb(self, action):
        self.options['followchanged'] = self.followchanged_toggleaction.get_active()

    def reload_action_activate_cb(self, widget):
        self.device_finder.scan_subsystems(DEFAULT_SUBSYSTEMS, 
            self.options['parent_tree'])

        self.populate(self.device_finder.get_devices())
        self.expand_toggleaction_toggled_cb(self.expand_toggleaction)

    def devices_tv_cursor_changed_cb(self, treeview):
        selection = self.devices_tv.get_selection()
        model, selected = selection.get_selected()

        if selected:
            row = model[selected]
            device = self.device_finder.get_devices_tree()[row[PATH_COL]]

            title = '<b>'+device.nice_label+'</b>'
            if hasattr(device, 'vendor_name'):
                title += '\n<i>%s</i>' % device.vendor_name
            if hasattr(device, 'model_name'):
                title += '\n<i>%s</i>' % device.model_name
            self.devicename_label.set_label(title)

            desc = '\n'.join([': '.join(('<b>'+key.capitalize()+'</b>', 
                str(val))) for key, val in device.get_info()])
            self.devicedesc_label.set_label(desc)

            self.device_image.set_from_icon_name(device.icon, gtk.ICON_SIZE_DIALOG)

            if hasattr(device, 'get_summary'):
                self.summary_scrollwindow.set_visible(True)
                desc = '\n'.join([': '.join(('<b>'+key.capitalize()+'</b>', 
                    str(val))) for key, val in device.get_summary()])
                self.devicepropsum_label.set_label(desc)
            else:
                self.summary_scrollwindow.set_visible(False)

            self.deviceprop_store.clear()
            for key, val in device.get_props().items():
                self.deviceprop_store.append([key, 
                    val.decode("string-escape")])

    def search_entry_activate_cb(self, entry):
        search_text = entry.get_text().lower()
        if not search_text:
            return

        def update_visible(treeiter):
            """ Finds the search string and marks node as visible """
            treerow = self.devices_treestore[treeiter]
            device = self.device_finder.get_devices_tree()[treerow[PATH_COL]]
            visible = False

            # Matching device name, nice_label, vendor and model            
            if (search_text in device.nice_label.lower()) or \
                    (search_text in device.device.get_name().lower()) or \
                    (hasattr(device, 'vendor_name') and device.vendor_name and \
                        search_text in device.vendor_name.lower()) or \
                    (hasattr(device, 'model_name') and device.model_name and \
                        search_text in device.model_name.lower()):
                visible = True

            # Matching udev device static info
            for key, val in device.get_info():
                if search_text in str(val).lower():
                    visible = True

            # Matching udev device properties
            for key, val in device.get_props().items():
                if search_text in str(key).lower() or \
                        search_text in str(val).lower():
                    visible = True

            # Matching optional udevdiscover device summary info
            if hasattr(device, 'get_summary'):
                for key, val in device.get_summary():
                    if search_text in str(val).lower():
                        visible = True

            treerow[VISIBLE_COL] = visible
            return visible

        visible_iter = []
        for path in self.rows.keys():
            iter = self.devices_treestore.get_iter(self.rows[path].get_path())
            if update_visible(iter):
                visible_iter.append(iter)

        if visible_iter:
            def set_branch_visible(itr):
                """ Sets the whole tree-branch upward as visible """
                tr = self.devices_treestore[itr]
                tr[VISIBLE_COL] = True
                itr_prnt = self.devices_treestore.iter_parent(itr)
                if itr_prnt:
                    set_branch_visible(itr_prnt)

            for iter in visible_iter:
                iter_parent = self.devices_treestore.iter_parent(iter)
                if iter_parent:
                    set_branch_visible(iter_parent)

        self.showparents_toggleaction.set_sensitive(False)
        modelfilter = self.devices_treestore.filter_new()
        modelfilter.set_visible_column(VISIBLE_COL)

        """
        # DEBUGGING
        for i in [v.get_model()[v.get_path()][NAME_COL] for v in self.rows.values() if \
                v.get_model()[v.get_path()][VISIBLE_COL] == True]:
            print i
        print '--------------- ROWS ------------------'        
        def a(model, path, iter, val):
            print model[iter][NAME_COL]
        modelfilter.foreach(a, None)
        print '--------------- MODELFILTER ------------------'
        # DEBUGGING
        """

        self.devices_tv.set_model(modelfilter)
        self.expand_toggleaction_toggled_cb(self.expand_toggleaction)

    def search_entry_changed_cb(self, entry):
        if entry.get_text():
            entry.set_property('primary-icon-sensitive',True)
            entry.set_property('secondary-icon-sensitive',True)
        else:
            self.devices_tv.set_model(self.devices_treestore)
            self.expand_toggleaction_toggled_cb(self.expand_toggleaction)
            self.showparents_toggleaction.set_sensitive(True)
            entry.set_property('primary-icon-sensitive',False)
            entry.set_property('secondary-icon-sensitive',False)

    def search_entry_icon_release_cb(self, entry, icon_pos, event):
        if icon_pos == 0:
            entry.set_text('')
            self.devices_tv.set_model(self.devices_treestore)
            self.expand_toggleaction_toggled_cb(self.expand_toggleaction)
        else:
            self.search_entry_activate_cb(entry)

    def about_action_activate_cb(self, widget):
        self.about_dialog.run()

    def help_action_activate_cb(self, widget):
        pass

    def quit_action_activate_cb(self, data=None):
        self.options['devices_hpaned'] = self.devices_hpaned.get_position()
        self.options['eventslog_vpaned'] = self.eventslog_vpaned.get_position()
        self.options['eventslog_expanded'] = self.eventslog_expander.get_expanded()
        self.options['follownew'] = self.follownew_toggleaction.get_active()
        self.options['followchanged'] = self.followchanged_toggleaction.get_active()
        self.saveconf()
        sys.exit(0)

if __name__ == '__main__':
    UDevDiscoverGUI()
    gobject.MainLoop().run()
